---
title: "Bayes Final Project"
author: "Taylor Fortnam"
date: "April 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)

```

```{r}
library(rjags)
library(jagsUI)
library(gemtc)
library(pcnetmeta)

df=read.csv("/Users/cramptonhelms/Downloads/data.csv", header=T, skip=2, stringsAsFactors=F)[1:1199 , 1:19]
head(df)
df[ , "Dosage"] <- NA

#print(grep(" ", df$Drug, value=T))
#print(sapply(df$Drug[grep(" ", df$Drug)], function(x) sub(".* ", "", x)))

df$Dosage[grep(" ", df$Drug)] <- sapply(df$Drug[grep(" ", df$Drug)], function(x) sub(".* ", "", x))  # If it contains a space, extract everything after first space (dosage)

#print(df$Dosage)
#df$Dosage <- sapply(df$Drug, function(x) ifelse(grep(" ", x), sub(".* ", "", x), 0))
#print(df$Dosage)

df$Drug <- sapply(df$Drug, function(x) tolower(sub(" .*", "", x)))  # Takes care of Placebo / placebo being separate
print(unique(df$Drug))
length(unique(df$StudyID)) # 522
length(unique(df$Drug))  # 22
length(unique(df$Dosage))  # 39 but includes NA'
print(unique(df$Definition.of.response))
df$Responders <- as.numeric(df$Responders)
df$No_randomised <- as.numeric(df$No_randomised)
str(df)

# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4277278/
#jags(df, parameters.to.save=c(df$Drug, df$response), n.iter=20)  # Not right... use this or rank.probability from gemtc
# 
#  BELOW EXAMPLE IS FROM JAGS FUNCTION DOCUMENTATION
# writeLines("
# model{
#            
#            #Likelihood
#            for (i in 1:n){ 
#            
#            employed[i] ~ dnorm(mu[i], tau)     
#            mu[i] <- alpha + beta*gnp[i]
#            
#            }
#            
#            #Priors
#            alpha ~ dnorm(0, 0.00001)
#            beta ~ dnorm(0, 0.00001)
#            sigma ~ dunif(0,1000)
#            tau <- pow(sigma,-2)
#            
#            }
#            ", con="model.txt")
# 
# #Identify filepath of model file;
# #in this case in the working directory
# modfile <- 'model.txt'
#print(df)
nma.networkplot(StudyID, Drug, df)
df <- df[!is.na(df$Responders), ]

nma.ab.bin(StudyID, Drug, Responders, No_randomised, df, digits=3, conv.diag=T, dic=T, postdens=T, higher.better=T, n.iter=1000, n.burnin=100)
```
